# Generated by Django 5.2.10 on 2026-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='access_level',
            field=models.CharField(choices=[('All', 'Tous'), ('Teacher', 'Enseignant uniquement')], default='All', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
